print("Please enter the ammount of lives")
lives=str(input())
print("Please enter the energy level")
energy=int(input())
print("Please enter the shield level")
shield=int(input())
print(f"Lives:  {'♥' * lives}")
print(f"Energy: {'♦' * energy}")
print(f"Shield: {'♦' * shield}")